version: "3"

services:

  discovery-service:
    build: ./discovery-service
    ports:
      - "10000:10000"

  configuration-service:
    build: ./configuration-service
    ports:
      - "10001:10001"
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=discovery-service
    depends_on:
      - discovery-service

  gateway-service:
    build: ./inventory-service
    ports:
      - "8100:8100"
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=discovery-service -DCONFIG_SERVER=configuration-service
    depends_on:
      - discovery-service
      - configuration-service

  user-service:
    build: ./inventory-service
    ports:
      - "8100:8100"
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=discovery-service -DCONFIG_SERVER=configuration-service
    depends_on:
      - discovery-service
      - configuration-service

  authentication-service:
    build: ./authentication-service
    ports:
      - "8000:8000"
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=discovery-service -DCONFIG_SERVER=configuration-service
    depends_on:
      - discovery-service
      - configuration-service
